compiler_command = "tools/ido-cc -c -O2 -mips1 -G 0 -non_shared -fullwarn -Xcpluscomm -nostdinc -Wab,-r4300_mul -woff 649,838,712,516 -Iinclude -DPERMUTER"

assembler_command = "tools/n64-as -EB -march=vr4300 -mtune=vr4300 -Iinclude -mabi=32"

compiler_type = "ido"

[preserve_macros]
"MIN" = "int"
"MAX" = "int"
"ABS" = "int"
"NULL" = "void*"

[decompme.compilers]
"tools/ido-cc" = "ido5.3"
